### ISSUE TITLE
Gauntlet (Rev 14) on Mister FPGA - HDMI/DVI - Right portion of screen cut-off

### ISSUE THREAD

**Issue by tritanium1** [d18c7db/Gauntlet_FPGA#14]
On HDMI display, screen is cutoff on right-side.  Approximately two-thirds of horizontal display appears.  I can only see the first couple of letters of text on the right side.  Black bar beyond that.

Tried setting DVI=1 in mister .ini settings file, but this did not correct the issue.

**Comment by d18c7db** [comment]
Yeah I think this is due to the screen buffer being too small. This issue doesn’t show on VGA or DVI. Unfortunately the screen buffer can’t be increased yet because there is insufficient memory on the FPGA so some ROMs must be moved onto the SDRAM which is something I’m working on right now. After that, this will be sorted too.

**Comment by tritanium1** [comment]
I actually found that my issue seemed to be related to rotating the Mister osd (osd_rotate =1 in mister.ini file).  I had the osd rotated because most of the arcade games I was testing were older portrait mode games.  Once I set the parameter to osd_rotate = 0, the issue was resolved!
