### ISSUE TITLE
Audio is too high pitched

### ISSUE THREAD

**Issue by rhester72** [d18c7db/Gauntlet_FPGA#2]
On MiSTer (can't speak for other targets), all audio (including voice) sounds about one octave too high.

I'm not sure if it's related, but the sound of f.e. ghosts hitting warrior on level one sounds like popping bubbles...not sure how else to describe it.  =)

**Comment by dfilskov** [comment]
I'm using the core from August 12th - doesn't the audio sound right?

[Gauntlet_Aug_15_2020-mp3.zip](https://github.com/d18c7db/Gauntlet_FPGA/files/5077667/Gauntlet_Aug_15_2020-mp3.zip)

**Comment by rhester72** [comment]
Nope...those are definitely pitched too high.

See gameplay from the end of this video (starting around the 1h15m mark):

https://www.youtube.com/watch?v=OmkI4Kalckw

**Comment by dfilskov** [comment]
OK, I'll get back with a comparison :)

It's not an octave higher, though, since that's the double tempo / twice the frequency - it's much less.

I'll check what the difference is more precisely.

**Comment by d18c7db** [comment]
First off you guys are comparing against a YouTube video of MAME gameplay in an echoey room, not a real arcade. Secondly if you want a better comparison set both MAME and MiSTer game in system test mode, go to sound test and compare each individual sound against each other. There are three different sound sources, the YM2151 the Pokey and the TMS5220. Do all of them sound wrong or just some?

When I get home from holiday I can investigate myself.


On 15/08/2020, at 09:31, dfilskov <notifications@github.com<mailto:notifications@github.com>> wrote:


OK, I'll get back with a comparison :)

It's not an octave higher, though, since that's the double tempo / twice the frequency - it's much less.

I'll check what the difference is more precisely.

**Comment by dfilskov** [comment]
Sounds great, Alex! - thanks! - I'll do a comparison to one of these instead: https://www.youtube.com/watch?v=svzYT6qN7cE or https://www.youtube.com/watch?v=TtNv4AlJhQM

**Comment by dfilskov** [comment]
Sounds great, Alex! - thanks a lot!

I've done a comparison to this video now: https://www.youtube.com/watch?v=svzYT6qN7cE - **The FM** (but not the voice) seems to be **exactly one octave too high**. When I pitch down e.g. the coin sounds (tubular bells like) one octave (= 12 notes) they match perfectly with the original from the video.

I've made an MP3 where I alternate between first the MiSTer - which sounds a bit thin and high-pitched - and then the original - lower/more deep and "scary"  - back and forth :) - also I've included the coin sounds ... and after those I've pitched down the MiSTer recordings so that you can hear that they actually end up matching the original from the video (both the coin sounds and the main theme sounds correct when pitched down to half the frequency).

[FM_should_be_half_the_frequency.zip](https://github.com/d18c7db/Gauntlet_FPGA/files/5078495/FM_should_be_half_the_frequency.zip)

**Comment by d18c7db** [comment]
I saw what the problem was, confusing multiple clock enables on the jt51 core, should be fixed now.

**Comment by rhester72** [comment]
Perfect, thank you very much!
