### ISSUE TITLE
MiSTer - welcome voice and names only play occasionally

### ISSUE THREAD

**Issue by dfilskov** [d18c7db/Gauntlet_FPGA#8]
I think the voice should say at least "Welcome" each time a new player joins and at least sometimes followed by a character name - "Blue Valkyrie" for instance.

But often only the sound effect is heard - no voice - or just "Welcome" on top of the sound effect - no name.

I've tried resetting and joining two players and recorded it three times in a row - I couldn't get it to say the names on video. Only once have I heard a name after "welcome" - that was Blue Valkyrie.

https://www.dropbox.com/s/s49mdm4htzlck2s/Gauntlet%20welcome%20and%20names%20missing.mp4?dl=0

**Comment by d18c7db** [comment]
You have to be more specific, which romset are you using?
Does MAME behave differently with the same romset?

Are you perhaps confusing games? Gauntlet has fixed colors for the players (so always warrior=red, valk=blue, wiz=yellow and elf=green) so it's pointless to announce the player color.

As far as I know the only game that announces player color is Gauntlet II because you can chose what character you play with so for example yellow player can chose elf and also red player can chose elf, so you could have a yellow elf and a red elf for example hence the player color announcement.

All in all, all I did is the equivalent of "plugging some virtual chips in a virtual motherboard", I didn't change the game software or behaviour, so I don't control the voice announcements, from a hardware perspective, they either work or they don't, there's no "they work sometimes"...

**Comment by dfilskov** [comment]
Sorry - the color was only my imagination (probably from back then) ... but please check out the original here at 20:14 ("Welcome Elf") - and six seconds later at 20:20 ("Welcome Warrior") - can you make this core do that every time? - or could it perhaps be "fixable"? - maybe it's simply depends on the ROM version? - that rev 14 simply often mutes the "Welcome" and names announcements for some reason?

https://youtu.be/6QzFNU3hs3Q?t=1210

**Comment by d18c7db** [comment]
Well can you run MAME and find me a romset that does that "every time" because i've run all the roms i have through MAME and they only ever say "welcome", very rarely they will say "welcome wizard" or whatever character.

As i've said the hardware either works or it doesn't, there is nothing at the hardware level I can think of that makes the "welcome" sound then stops the character announcement. That's all in the ROMs/software.

**Comment by dfilskov** [comment]
That makes sense - thanks for the explanation! - I'll look into this weird deviation.
